In [1]:
%matplotlib inline
from matplotlib import style
style.use('fivethirtyeight')
import matplotlib.pyplot as plt

In [2]:
import numpy as np
import pandas as pd

In [3]:
import datetime as dt

# Reflect Tables into SQLAlchemy ORM

In [4]:
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

In [5]:
# reflect an existing database into a new model
# reflect the tables
engine = create_engine("sqlite:///hawaii.sqlite")

In [6]:
# We can view all of the classes that automap found
Base = automap_base()
Base.prepare(engine, reflect=True)
Base.classes.keys()

['measurement', 'station']

In [7]:
# Save references to each table
Measurement = Base.classes.measurement
Station = Base.classes.station

In [8]:
# Create our session (link) from Python to the DB
session = Session(engine)

# Exploratory Climate Analysis

In [9]:
# Create previous month
start_december = dt.date(2016, 12, 1)
end_december = dt.date(2016, 12, 31)

In [10]:
# Write a query that filters the date column from the Measurement table to retrieve all the temperatures for the month of December.
results = []
results = session.query(Measurement.date, Measurement.tobs).filter(Measurement.date >= start_december).filter(Measurement.date <= end_december).all()
print(results)

[('2016-12-01', 75.0), ('2016-12-02', 72.0), ('2016-12-03', 69.0), ('2016-12-04', 71.0), ('2016-12-05', 68.0), ('2016-12-06', 67.0), ('2016-12-07', 69.0), ('2016-12-08', 73.0), ('2016-12-09', 70.0), ('2016-12-10', 70.0), ('2016-12-11', 70.0), ('2016-12-12', 66.0), ('2016-12-13', 67.0), ('2016-12-14', 70.0), ('2016-12-15', 66.0), ('2016-12-16', 62.0), ('2016-12-17', 71.0), ('2016-12-18', 73.0), ('2016-12-19', 69.0), ('2016-12-20', 77.0), ('2016-12-21', 74.0), ('2016-12-22', 71.0), ('2016-12-23', 72.0), ('2016-12-24', 74.0), ('2016-12-25', 74.0), ('2016-12-26', 74.0), ('2016-12-27', 74.0), ('2016-12-28', 71.0), ('2016-12-29', 73.0), ('2016-12-30', 69.0), ('2016-12-31', 66.0), ('2016-12-01', 73.0), ('2016-12-02', 71.0), ('2016-12-03', 71.0), ('2016-12-04', 69.0), ('2016-12-05', 68.0), ('2016-12-06', 70.0), ('2016-12-07', 71.0), ('2016-12-08', 72.0), ('2016-12-09', 70.0), ('2016-12-10', 71.0), ('2016-12-11', 72.0), ('2016-12-12', 68.0), ('2016-12-13', 68.0), ('2016-12-14', 70.0), ('2016-12-15', 70.0), ('2016-12-16', 63.0), ('2016-12-17', 71.0), ('2016-12-18', 67.0), ('2016-12-19', 69.0), ('2016-12-20', 74.0), ('2016-12-21', 72.0), ('2016-12-22', 70.0), ('2016-12-23', 69.0), ('2016-12-24', 73.0), ('2016-12-25', 74.0), ('2016-12-26', 74.0), ('2016-12-27', 73.0), ('2016-12-28', 71.0), ('2016-12-29', 72.0), ('2016-12-30', 69.0), ('2016-12-31', 71.0), ('2016-12-01', 75.0), ('2016-12-02', 77.0), ('2016-12-03', 75.0), ('2016-12-04', 77.0), ('2016-12-05', 76.0), ('2016-12-07', 76.0), ('2016-12-08', 75.0), ('2016-12-09', 72.0), ('2016-12-10', 76.0), ('2016-12-12', 75.0), ('2016-12-13', 72.0), ('2016-12-14', 72.0), ('2016-12-15', 75.0), ('2016-12-16', 69.0), ('2016-12-17', 75.0), ('2016-12-18', 74.0), ('2016-12-19', 78.0), ('2016-12-20', 77.0), ('2016-12-21', 76.0), ('2016-12-22', 72.0), ('2016-12-23', 73.0), ('2016-12-24', 74.0), ('2016-12-26', 74.0), ('2016-12-27', 74.0), ('2016-12-28', 73.0), ('2016-12-29', 73.0), ('2016-12-30', 71.0), ('2016-12-31', 72.0), ('2016-12-01', 72.0), ('2016-12-02', 70.0), ('2016-12-05', 68.0), ('2016-12-06', 74.0), ('2016-12-07', 71.0), ('2016-12-08', 70.0), ('2016-12-09', 70.0), ('2016-12-12', 70.0), ('2016-12-13', 68.0), ('2016-12-14', 68.0), ('2016-12-15', 68.0), ('2016-12-16', 66.0), ('2016-12-19', 71.0), ('2016-12-20', 76.0), ('2016-12-21', 73.0), ('2016-12-22', 70.0), ('2016-12-23', 68.0), ('2016-12-28', 71.0), ('2016-12-29', 71.0), ('2016-12-30', 68.0), ('2016-12-01', 76.0), ('2016-12-02', 75.0), ('2016-12-03', 75.0), ('2016-12-04', 75.0), ('2016-12-05', 70.0), ('2016-12-06', 70.0), ('2016-12-07', 74.0), ('2016-12-08', 73.0), ('2016-12-10', 72.0), ('2016-12-11', 78.0), ('2016-12-12', 67.0), ('2016-12-13', 69.0), ('2016-12-14', 71.0), ('2016-12-15', 74.0), ('2016-12-16', 63.0), ('2016-12-17', 76.0), ('2016-12-18', 76.0), ('2016-12-19', 71.0), ('2016-12-20', 76.0), ('2016-12-21', 77.0), ('2016-12-22', 73.0), ('2016-12-23', 71.0), ('2016-12-24', 78.0), ('2016-12-25', 78.0), ('2016-12-26', 75.0), ('2016-12-27', 75.0), ('2016-12-28', 72.0), ('2016-12-29', 77.0), ('2016-12-30', 72.0), ('2016-12-01', 74.0), ('2016-12-02', 70.0), ('2016-12-03', 72.0), ('2016-12-04', 70.0), ('2016-12-05', 67.0), ('2016-12-06', 67.0), ('2016-12-07', 69.0), ('2016-12-08', 70.0), ('2016-12-09', 68.0), ('2016-12-10', 69.0), ('2016-12-11', 69.0), ('2016-12-12', 66.0), ('2016-12-13', 65.0), ('2016-12-14', 68.0), ('2016-12-15', 62.0), ('2016-12-16', 75.0), ('2016-12-17', 70.0), ('2016-12-18', 69.0), ('2016-12-19', 76.0), ('2016-12-20', 76.0), ('2016-12-21', 74.0), ('2016-12-22', 73.0), ('2016-12-23', 71.0), ('2016-12-24', 74.0), ('2016-12-25', 74.0), ('2016-12-26', 72.0), ('2016-12-27', 71.0), ('2016-12-28', 72.0), ('2016-12-29', 74.0), ('2016-12-30', 69.0), ('2016-12-31', 67.0), ('2016-12-01', 71.0), ('2016-12-02', 71.0), ('2016-12-03', 67.0), ('2016-12-04', 76.0), ('2016-12-05', 67.0), ('2016-12-06', 67.0), ('2016-12-07', 68.0), ('2016-12-08', 71.0), ('2016-12-09', 68.0), ('2016-12-10', 68.0), ('2016-12-11', 69.0), ('2016-12-12', 65.0), ('2016-12-13', 70.0), ('2016-12-14', 69.0), ('2016-12-15', 64.0), ('2016-12-16', 60.0), ('2016-12-18', 67.0), ('2016-12-19', 72.0), ('2016-12-20', 73.0), ('2016-12-21', 70.0), ('2016-12-22', 68.0), ('2016-12-23', 69.0), ('2016-12-24', 69.0), ('2016-12-25', 69.0), ('2016-12-26', 71.0), ('2016-12-27', 71.0), ('2016-12-28', 71.0), ('2016-12-29', 69.0), ('2016-12-30', 65.0), ('2016-12-31', 65.0)]

In [11]:
# Save the query results as a Pandas DataFrame and set the index to the date column
df = pd.DataFrame(results, columns=['date','temperature'])
df.set_index(df['date'], inplace=True)
print(df)

                  date  temperature
date
2016-12-01  2016-12-01         75.0
2016-12-02  2016-12-02         72.0
2016-12-03  2016-12-03         69.0
2016-12-04  2016-12-04         71.0
2016-12-05  2016-12-05         68.0
...                ...          ...
2016-12-27  2016-12-27         71.0
2016-12-28  2016-12-28         71.0
2016-12-29  2016-12-29         69.0
2016-12-30  2016-12-30         65.0
2016-12-31  2016-12-31         65.0

[200 rows x 2 columns]

In [12]:
print(df.to_string(index=False))

       date  temperature
 2016-12-01         75.0
 2016-12-02         72.0
 2016-12-03         69.0
 2016-12-04         71.0
 2016-12-05         68.0
 2016-12-06         67.0
 2016-12-07         69.0
 2016-12-08         73.0
 2016-12-09         70.0
 2016-12-10         70.0
 2016-12-11         70.0
 2016-12-12         66.0
 2016-12-13         67.0
 2016-12-14         70.0
 2016-12-15         66.0
 2016-12-16         62.0
 2016-12-17         71.0
 2016-12-18         73.0
 2016-12-19         69.0
 2016-12-20         77.0
 2016-12-21         74.0
 2016-12-22         71.0
 2016-12-23         72.0
 2016-12-24         74.0
 2016-12-25         74.0
 2016-12-26         74.0
 2016-12-27         74.0
 2016-12-28         71.0
 2016-12-29         73.0
 2016-12-30         69.0
 2016-12-31         66.0
 2016-12-01         73.0
 2016-12-02         71.0
 2016-12-03         71.0
 2016-12-04         69.0
 2016-12-05         68.0
 2016-12-06         70.0
 2016-12-07         71.0
 2016-12-08         72.0
 2016-12-09         70.0
 2016-12-10         71.0
 2016-12-11         72.0
 2016-12-12         68.0
 2016-12-13         68.0
 2016-12-14         70.0
 2016-12-15         70.0
 2016-12-16         63.0
 2016-12-17         71.0
 2016-12-18         67.0
 2016-12-19         69.0
 2016-12-20         74.0
 2016-12-21         72.0
 2016-12-22         70.0
 2016-12-23         69.0
 2016-12-24         73.0
 2016-12-25         74.0
 2016-12-26         74.0
 2016-12-27         73.0
 2016-12-28         71.0
 2016-12-29         72.0
 2016-12-30         69.0
 2016-12-31         71.0
 2016-12-01         75.0
 2016-12-02         77.0
 2016-12-03         75.0
 2016-12-04         77.0
 2016-12-05         76.0
 2016-12-07         76.0
 2016-12-08         75.0
 2016-12-09         72.0
 2016-12-10         76.0
 2016-12-12         75.0
 2016-12-13         72.0
 2016-12-14         72.0
 2016-12-15         75.0
 2016-12-16         69.0
 2016-12-17         75.0
 2016-12-18         74.0
 2016-12-19         78.0
 2016-12-20         77.0
 2016-12-21         76.0
 2016-12-22         72.0
 2016-12-23         73.0
 2016-12-24         74.0
 2016-12-26         74.0
 2016-12-27         74.0
 2016-12-28         73.0
 2016-12-29         73.0
 2016-12-30         71.0
 2016-12-31         72.0
 2016-12-01         72.0
 2016-12-02         70.0
 2016-12-05         68.0
 2016-12-06         74.0
 2016-12-07         71.0
 2016-12-08         70.0
 2016-12-09         70.0
 2016-12-12         70.0
 2016-12-13         68.0
 2016-12-14         68.0
 2016-12-15         68.0
 2016-12-16         66.0
 2016-12-19         71.0
 2016-12-20         76.0
 2016-12-21         73.0
 2016-12-22         70.0
 2016-12-23         68.0
 2016-12-28         71.0
 2016-12-29         71.0
 2016-12-30         68.0
 2016-12-01         76.0
 2016-12-02         75.0
 2016-12-03         75.0
 2016-12-04         75.0
 2016-12-05         70.0
 2016-12-06         70.0
 2016-12-07         74.0
 2016-12-08         73.0
 2016-12-10         72.0
 2016-12-11         78.0
 2016-12-12         67.0
 2016-12-13         69.0
 2016-12-14         71.0
 2016-12-15         74.0
 2016-12-16         63.0
 2016-12-17         76.0
 2016-12-18         76.0
 2016-12-19         71.0
 2016-12-20         76.0
 2016-12-21         77.0
 2016-12-22         73.0
 2016-12-23         71.0
 2016-12-24         78.0
 2016-12-25         78.0
 2016-12-26         75.0
 2016-12-27         75.0
 2016-12-28         72.0
 2016-12-29         77.0
 2016-12-30         72.0
 2016-12-01         74.0
 2016-12-02         70.0
 2016-12-03         72.0
 2016-12-04         70.0
 2016-12-05         67.0
 2016-12-06         67.0
 2016-12-07         69.0
 2016-12-08         70.0
 2016-12-09         68.0
 2016-12-10         69.0
 2016-12-11         69.0
 2016-12-12         66.0
 2016-12-13         65.0
 2016-12-14         68.0
 2016-12-15         62.0
 2016-12-16         75.0
 2016-12-17         70.0
 2016-12-18         69.0
 2016-12-19         76.0
 2016-12-20         76.0
 2016-12-21         74.0
 2016-12-22         73.0
 2016-12-23         71.0
 2016-12-24         74.0
 2016-12-25         74.0
 2016-12-26         72.0
 2016-12-27         71.0
 2016-12-28         72.0
 2016-12-29         74.0
 2016-12-30         69.0
 2016-12-31         67.0
 2016-12-01         71.0
 2016-12-02         71.0
 2016-12-03         67.0
 2016-12-04         76.0
 2016-12-05         67.0
 2016-12-06         67.0
 2016-12-07         68.0
 2016-12-08         71.0
 2016-12-09         68.0
 2016-12-10         68.0
 2016-12-11         69.0
 2016-12-12         65.0
 2016-12-13         70.0
 2016-12-14         69.0
 2016-12-15         64.0
 2016-12-16         60.0
 2016-12-18         67.0
 2016-12-19         72.0
 2016-12-20         73.0
 2016-12-21         70.0
 2016-12-22         68.0
 2016-12-23         69.0
 2016-12-24         69.0
 2016-12-25         69.0
 2016-12-26         71.0
 2016-12-27         71.0
 2016-12-28         71.0
 2016-12-29         69.0
 2016-12-30         65.0
 2016-12-31         65.0

In [13]:
# Sort the dataframe by date
df = df.sort_index()
print(df.to_string(index=False))

       date  temperature
 2016-12-01         75.0
 2016-12-01         76.0
 2016-12-01         75.0
 2016-12-01         74.0
 2016-12-01         73.0
 2016-12-01         71.0
 2016-12-01         72.0
 2016-12-02         71.0
 2016-12-02         70.0
 2016-12-02         70.0
 2016-12-02         72.0
 2016-12-02         75.0
 2016-12-02         77.0
 2016-12-02         71.0
 2016-12-03         75.0
 2016-12-03         72.0
 2016-12-03         75.0
 2016-12-03         67.0
 2016-12-03         69.0
 2016-12-03         71.0
 2016-12-04         76.0
 2016-12-04         77.0
 2016-12-04         69.0
 2016-12-04         71.0
 2016-12-04         75.0
 2016-12-04         70.0
 2016-12-05         68.0
 2016-12-05         68.0
 2016-12-05         67.0
 2016-12-05         67.0
 2016-12-05         76.0
 2016-12-05         68.0
 2016-12-05         70.0
 2016-12-06         67.0
 2016-12-06         67.0
 2016-12-06         70.0
 2016-12-06         74.0
 2016-12-06         70.0
 2016-12-06         67.0
 2016-12-07         69.0
 2016-12-07         69.0
 2016-12-07         71.0
 2016-12-07         74.0
 2016-12-07         71.0
 2016-12-07         76.0
 2016-12-07         68.0
 2016-12-08         73.0
 2016-12-08         75.0
 2016-12-08         70.0
 2016-12-08         73.0
 2016-12-08         70.0
 2016-12-08         71.0
 2016-12-08         72.0
 2016-12-09         70.0
 2016-12-09         70.0
 2016-12-09         72.0
 2016-12-09         68.0
 2016-12-09         68.0
 2016-12-09         70.0
 2016-12-10         69.0
 2016-12-10         70.0
 2016-12-10         76.0
 2016-12-10         68.0
 2016-12-10         71.0
 2016-12-10         72.0
 2016-12-11         72.0
 2016-12-11         78.0
 2016-12-11         70.0
 2016-12-11         69.0
 2016-12-11         69.0
 2016-12-12         66.0
 2016-12-12         68.0
 2016-12-12         66.0
 2016-12-12         70.0
 2016-12-12         65.0
 2016-12-12         75.0
 2016-12-12         67.0
 2016-12-13         70.0
 2016-12-13         67.0
 2016-12-13         68.0
 2016-12-13         69.0
 2016-12-13         65.0
 2016-12-13         72.0
 2016-12-13         68.0
 2016-12-14         69.0
 2016-12-14         71.0
 2016-12-14         68.0
 2016-12-14         68.0
 2016-12-14         72.0
 2016-12-14         70.0
 2016-12-14         70.0
 2016-12-15         62.0
 2016-12-15         75.0
 2016-12-15         70.0
 2016-12-15         68.0
 2016-12-15         74.0
 2016-12-15         66.0
 2016-12-15         64.0
 2016-12-16         69.0
 2016-12-16         63.0
 2016-12-16         66.0
 2016-12-16         75.0
 2016-12-16         63.0
 2016-12-16         62.0
 2016-12-16         60.0
 2016-12-17         75.0
 2016-12-17         71.0
 2016-12-17         70.0
 2016-12-17         76.0
 2016-12-17         71.0
 2016-12-18         73.0
 2016-12-18         67.0
 2016-12-18         67.0
 2016-12-18         74.0
 2016-12-18         69.0
 2016-12-18         76.0
 2016-12-19         69.0
 2016-12-19         76.0
 2016-12-19         71.0
 2016-12-19         69.0
 2016-12-19         72.0
 2016-12-19         71.0
 2016-12-19         78.0
 2016-12-20         76.0
 2016-12-20         73.0
 2016-12-20         74.0
 2016-12-20         77.0
 2016-12-20         76.0
 2016-12-20         76.0
 2016-12-20         77.0
 2016-12-21         77.0
 2016-12-21         74.0
 2016-12-21         74.0
 2016-12-21         72.0
 2016-12-21         76.0
 2016-12-21         70.0
 2016-12-21         73.0
 2016-12-22         72.0
 2016-12-22         70.0
 2016-12-22         70.0
 2016-12-22         71.0
 2016-12-22         73.0
 2016-12-22         73.0
 2016-12-22         68.0
 2016-12-23         71.0
 2016-12-23         69.0
 2016-12-23         73.0
 2016-12-23         72.0
 2016-12-23         71.0
 2016-12-23         68.0
 2016-12-23         69.0
 2016-12-24         69.0
 2016-12-24         74.0
 2016-12-24         74.0
 2016-12-24         74.0
 2016-12-24         78.0
 2016-12-24         73.0
 2016-12-25         74.0
 2016-12-25         74.0
 2016-12-25         74.0
 2016-12-25         69.0
 2016-12-25         78.0
 2016-12-26         74.0
 2016-12-26         74.0
 2016-12-26         72.0
 2016-12-26         71.0
 2016-12-26         74.0
 2016-12-26         75.0
 2016-12-27         74.0
 2016-12-27         71.0
 2016-12-27         73.0
 2016-12-27         74.0
 2016-12-27         71.0
 2016-12-27         75.0
 2016-12-28         73.0
 2016-12-28         71.0
 2016-12-28         72.0
 2016-12-28         72.0
 2016-12-28         71.0
 2016-12-28         71.0
 2016-12-28         71.0
 2016-12-29         73.0
 2016-12-29         71.0
 2016-12-29         72.0
 2016-12-29         74.0
 2016-12-29         73.0
 2016-12-29         69.0
 2016-12-29         77.0
 2016-12-30         71.0
 2016-12-30         69.0
 2016-12-30         69.0
 2016-12-30         72.0
 2016-12-30         69.0
 2016-12-30         68.0
 2016-12-30         65.0
 2016-12-31         66.0
 2016-12-31         71.0
 2016-12-31         72.0
 2016-12-31         67.0
 2016-12-31         65.0

In [14]:
# Use Pandas to calcualte the summary statistics for the precipitation data
df.describe()

       temperature
count   200.000000
mean     71.130000
std       3.419292
min      60.000000
25%      69.000000
50%      71.000000
75%      74.000000
max      78.000000

# Challenge