In [1]:
%matplotlib inline
from matplotlib import style
style.use('fivethirtyeight')
import matplotlib.pyplot as plt

In [2]:
import numpy as np
import pandas as pd

In [3]:
import datetime as dt

# Reflect Tables into SQLAlchemy ORM

In [4]:
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

In [5]:
# reflect an existing database into a new model
# reflect the tables
engine = create_engine("sqlite:///hawaii.sqlite")

In [6]:
# We can view all of the classes that automap found
Base = automap_base()
Base.prepare(engine, reflect=True)
Base.classes.keys()

['measurement', 'station']

In [7]:
# Save references to each table
Measurement = Base.classes.measurement
Station = Base.classes.station

In [8]:
# Create our session (link) from Python to the DB
session = Session(engine)

# Exploratory Climate Analysis

In [9]:
# Create previous month
start_june = dt.date(2017, 6, 1)
end_june = dt.date(2017, 6, 30)

In [10]:
# Write a query that filters the date column from the Measurement table to retrieve all the temperatures for the month of June.
results = []
results = session.query(Measurement.date, Measurement.tobs).filter(Measurement.date >= start_june).filter(Measurement.date <= end_june).all()
print(results)

[('2017-06-01', 79.0), ('2017-06-02', 79.0), ('2017-06-03', 79.0), ('2017-06-04', 79.0), ('2017-06-05', 80.0), ('2017-06-06', 79.0), ('2017-06-07', 79.0), ('2017-06-08', 80.0), ('2017-06-09', 80.0), ('2017-06-10', 77.0), ('2017-06-11', 79.0), ('2017-06-12', 83.0), ('2017-06-13', 80.0), ('2017-06-14', 80.0), ('2017-06-15', 78.0), ('2017-06-16', 79.0), ('2017-06-17', 80.0), ('2017-06-18', 77.0), ('2017-06-19', 80.0), ('2017-06-20', 78.0), ('2017-06-21', 79.0), ('2017-06-22', 80.0), ('2017-06-23', 78.0), ('2017-06-24', 80.0), ('2017-06-25', 80.0), ('2017-06-26', 81.0), ('2017-06-27', 80.0), ('2017-06-28', 79.0), ('2017-06-29', 79.0), ('2017-06-30', 75.0), ('2017-06-01', 76.0), ('2017-06-02', 76.0), ('2017-06-03', 76.0), ('2017-06-04', 78.0), ('2017-06-05', 76.0), ('2017-06-06', 75.0), ('2017-06-07', 75.0), ('2017-06-08', 76.0), ('2017-06-09', 78.0), ('2017-06-10', 75.0), ('2017-06-11', 73.0), ('2017-06-12', 76.0), ('2017-06-13', 76.0), ('2017-06-14', 76.0), ('2017-06-15', 77.0), ('2017-06-16', 76.0), ('2017-06-17', 77.0), ('2017-06-18', 72.0), ('2017-06-19', 77.0), ('2017-06-20', 75.0), ('2017-06-21', 82.0), ('2017-06-22', 77.0), ('2017-06-23', 76.0), ('2017-06-24', 74.0), ('2017-06-25', 73.0), ('2017-06-26', 77.0), ('2017-06-27', 77.0), ('2017-06-28', 77.0), ('2017-06-29', 76.0), ('2017-06-30', 74.0), ('2017-06-01', 81.0), ('2017-06-02', 78.0), ('2017-06-03', 80.0), ('2017-06-04', 79.0), ('2017-06-05', 81.0), ('2017-06-06', 80.0), ('2017-06-07', 81.0), ('2017-06-08', 79.0), ('2017-06-09', 81.0), ('2017-06-10', 78.0), ('2017-06-11', 79.0), ('2017-06-12', 79.0), ('2017-06-13', 75.0), ('2017-06-14', 79.0), ('2017-06-15', 78.0), ('2017-06-16', 80.0), ('2017-06-17', 78.0), ('2017-06-18', 77.0), ('2017-06-19', 78.0), ('2017-06-20', 79.0), ('2017-06-23', 76.0), ('2017-06-26', 80.0), ('2017-06-29', 76.0), ('2017-06-30', 81.0), ('2017-06-02', 79.0), ('2017-06-05', 78.0), ('2017-06-06', 80.0), ('2017-06-07', 80.0), ('2017-06-08', 78.0), ('2017-06-09', 80.0), ('2017-06-13', 81.0), ('2017-06-14', 78.0), ('2017-06-15', 77.0), ('2017-06-16', 78.0), ('2017-06-19', 78.0), ('2017-06-20', 77.0), ('2017-06-21', 76.0), ('2017-06-22', 81.0), ('2017-06-23', 76.0), ('2017-06-26', 82.0), ('2017-06-27', 80.0), ('2017-06-28', 80.0), ('2017-06-29', 79.0), ('2017-06-30', 74.0), ('2017-06-01', 79.0), ('2017-06-02', 81.0), ('2017-06-03', 79.0), ('2017-06-04', 81.0), ('2017-06-05', 78.0), ('2017-06-06', 78.0), ('2017-06-07', 78.0), ('2017-06-08', 77.0), ('2017-06-09', 78.0), ('2017-06-10', 75.0), ('2017-06-11', 81.0), ('2017-06-12', 80.0), ('2017-06-13', 77.0), ('2017-06-14', 80.0), ('2017-06-15', 78.0), ('2017-06-16', 80.0), ('2017-06-17', 77.0), ('2017-06-18', 78.0), ('2017-06-19', 78.0), ('2017-06-21', 80.0), ('2017-06-22', 80.0), ('2017-06-23', 79.0), ('2017-06-24', 82.0), ('2017-06-25', 80.0), ('2017-06-26', 81.0), ('2017-06-27', 81.0), ('2017-06-28', 79.0), ('2017-06-29', 78.0), ('2017-06-30', 75.0), ('2017-06-01', 80.0), ('2017-06-02', 76.0), ('2017-06-03', 76.0), ('2017-06-04', 77.0), ('2017-06-05', 75.0), ('2017-06-06', 75.0), ('2017-06-07', 75.0), ('2017-06-08', 75.0), ('2017-06-09', 72.0), ('2017-06-10', 74.0), ('2017-06-11', 74.0), ('2017-06-12', 74.0), ('2017-06-13', 76.0), ('2017-06-14', 74.0), ('2017-06-15', 75.0), ('2017-06-16', 73.0), ('2017-06-17', 79.0), ('2017-06-18', 75.0), ('2017-06-19', 72.0), ('2017-06-20', 72.0), ('2017-06-21', 74.0), ('2017-06-22', 72.0), ('2017-06-23', 72.0), ('2017-06-24', 77.0), ('2017-06-25', 71.0), ('2017-06-26', 73.0), ('2017-06-27', 76.0), ('2017-06-28', 77.0), ('2017-06-29', 76.0), ('2017-06-30', 76.0), ('2017-06-01', 74.0), ('2017-06-03', 74.0), ('2017-06-04', 77.0), ('2017-06-05', 74.0), ('2017-06-06', 74.0), ('2017-06-07', 79.0), ('2017-06-08', 75.0), ('2017-06-10', 72.0), ('2017-06-11', 76.0), ('2017-06-12', 74.0), ('2017-06-13', 73.0), ('2017-06-14', 74.0), ('2017-06-15', 77.0), ('2017-06-16', 74.0), ('2017-06-17', 72.0), ('2017-06-18', 77.0), ('2017-06-19', 76.0), ('2017-06-20', 74.0), ('2017-06-21', 75.0), ('2017-06-22', 76.0), ('2017-06-23', 71.0), ('2017-06-24', 73.0), ('2017-06-25', 79.0), ('2017-06-26', 79.0), ('2017-06-27', 74.0), ('2017-06-28', 74.0), ('2017-06-29', 76.0), ('2017-06-30', 75.0)]

In [11]:
# Save the query results as a Pandas DataFrame and set the index to the date column
df = pd.DataFrame(results, columns=['date','temperature'])
df.set_index(df['date'], inplace=True)
print(df)

                  date  temperature
date
2017-06-01  2017-06-01         79.0
2017-06-02  2017-06-02         79.0
2017-06-03  2017-06-03         79.0
2017-06-04  2017-06-04         79.0
2017-06-05  2017-06-05         80.0
...                ...          ...
2017-06-26  2017-06-26         79.0
2017-06-27  2017-06-27         74.0
2017-06-28  2017-06-28         74.0
2017-06-29  2017-06-29         76.0
2017-06-30  2017-06-30         75.0

[191 rows x 2 columns]

In [12]:
print(df.to_string(index=False))

       date  temperature
 2017-06-01         79.0
 2017-06-02         79.0
 2017-06-03         79.0
 2017-06-04         79.0
 2017-06-05         80.0
 2017-06-06         79.0
 2017-06-07         79.0
 2017-06-08         80.0
 2017-06-09         80.0
 2017-06-10         77.0
 2017-06-11         79.0
 2017-06-12         83.0
 2017-06-13         80.0
 2017-06-14         80.0
 2017-06-15         78.0
 2017-06-16         79.0
 2017-06-17         80.0
 2017-06-18         77.0
 2017-06-19         80.0
 2017-06-20         78.0
 2017-06-21         79.0
 2017-06-22         80.0
 2017-06-23         78.0
 2017-06-24         80.0
 2017-06-25         80.0
 2017-06-26         81.0
 2017-06-27         80.0
 2017-06-28         79.0
 2017-06-29         79.0
 2017-06-30         75.0
 2017-06-01         76.0
 2017-06-02         76.0
 2017-06-03         76.0
 2017-06-04         78.0
 2017-06-05         76.0
 2017-06-06         75.0
 2017-06-07         75.0
 2017-06-08         76.0
 2017-06-09         78.0
 2017-06-10         75.0
 2017-06-11         73.0
 2017-06-12         76.0
 2017-06-13         76.0
 2017-06-14         76.0
 2017-06-15         77.0
 2017-06-16         76.0
 2017-06-17         77.0
 2017-06-18         72.0
 2017-06-19         77.0
 2017-06-20         75.0
 2017-06-21         82.0
 2017-06-22         77.0
 2017-06-23         76.0
 2017-06-24         74.0
 2017-06-25         73.0
 2017-06-26         77.0
 2017-06-27         77.0
 2017-06-28         77.0
 2017-06-29         76.0
 2017-06-30         74.0
 2017-06-01         81.0
 2017-06-02         78.0
 2017-06-03         80.0
 2017-06-04         79.0
 2017-06-05         81.0
 2017-06-06         80.0
 2017-06-07         81.0
 2017-06-08         79.0
 2017-06-09         81.0
 2017-06-10         78.0
 2017-06-11         79.0
 2017-06-12         79.0
 2017-06-13         75.0
 2017-06-14         79.0
 2017-06-15         78.0
 2017-06-16         80.0
 2017-06-17         78.0
 2017-06-18         77.0
 2017-06-19         78.0
 2017-06-20         79.0
 2017-06-23         76.0
 2017-06-26         80.0
 2017-06-29         76.0
 2017-06-30         81.0
 2017-06-02         79.0
 2017-06-05         78.0
 2017-06-06         80.0
 2017-06-07         80.0
 2017-06-08         78.0
 2017-06-09         80.0
 2017-06-13         81.0
 2017-06-14         78.0
 2017-06-15         77.0
 2017-06-16         78.0
 2017-06-19         78.0
 2017-06-20         77.0
 2017-06-21         76.0
 2017-06-22         81.0
 2017-06-23         76.0
 2017-06-26         82.0
 2017-06-27         80.0
 2017-06-28         80.0
 2017-06-29         79.0
 2017-06-30         74.0
 2017-06-01         79.0
 2017-06-02         81.0
 2017-06-03         79.0
 2017-06-04         81.0
 2017-06-05         78.0
 2017-06-06         78.0
 2017-06-07         78.0
 2017-06-08         77.0
 2017-06-09         78.0
 2017-06-10         75.0
 2017-06-11         81.0
 2017-06-12         80.0
 2017-06-13         77.0
 2017-06-14         80.0
 2017-06-15         78.0
 2017-06-16         80.0
 2017-06-17         77.0
 2017-06-18         78.0
 2017-06-19         78.0
 2017-06-21         80.0
 2017-06-22         80.0
 2017-06-23         79.0
 2017-06-24         82.0
 2017-06-25         80.0
 2017-06-26         81.0
 2017-06-27         81.0
 2017-06-28         79.0
 2017-06-29         78.0
 2017-06-30         75.0
 2017-06-01         80.0
 2017-06-02         76.0
 2017-06-03         76.0
 2017-06-04         77.0
 2017-06-05         75.0
 2017-06-06         75.0
 2017-06-07         75.0
 2017-06-08         75.0
 2017-06-09         72.0
 2017-06-10         74.0
 2017-06-11         74.0
 2017-06-12         74.0
 2017-06-13         76.0
 2017-06-14         74.0
 2017-06-15         75.0
 2017-06-16         73.0
 2017-06-17         79.0
 2017-06-18         75.0
 2017-06-19         72.0
 2017-06-20         72.0
 2017-06-21         74.0
 2017-06-22         72.0
 2017-06-23         72.0
 2017-06-24         77.0
 2017-06-25         71.0
 2017-06-26         73.0
 2017-06-27         76.0
 2017-06-28         77.0
 2017-06-29         76.0
 2017-06-30         76.0
 2017-06-01         74.0
 2017-06-03         74.0
 2017-06-04         77.0
 2017-06-05         74.0
 2017-06-06         74.0
 2017-06-07         79.0
 2017-06-08         75.0
 2017-06-10         72.0
 2017-06-11         76.0
 2017-06-12         74.0
 2017-06-13         73.0
 2017-06-14         74.0
 2017-06-15         77.0
 2017-06-16         74.0
 2017-06-17         72.0
 2017-06-18         77.0
 2017-06-19         76.0
 2017-06-20         74.0
 2017-06-21         75.0
 2017-06-22         76.0
 2017-06-23         71.0
 2017-06-24         73.0
 2017-06-25         79.0
 2017-06-26         79.0
 2017-06-27         74.0
 2017-06-28         74.0
 2017-06-29         76.0
 2017-06-30         75.0

In [13]:
# Sort the dataframe by date
df = df.sort_index()
print(df.to_string(index=False))

       date  temperature
 2017-06-01         79.0
 2017-06-01         79.0
 2017-06-01         81.0
 2017-06-01         74.0
 2017-06-01         76.0
 2017-06-01         80.0
 2017-06-02         76.0
 2017-06-02         78.0
 2017-06-02         79.0
 2017-06-02         76.0
 2017-06-02         81.0
 2017-06-02         79.0
 2017-06-03         79.0
 2017-06-03         76.0
 2017-06-03         74.0
 2017-06-03         80.0
 2017-06-03         76.0
 2017-06-03         79.0
 2017-06-04         79.0
 2017-06-04         81.0
 2017-06-04         77.0
 2017-06-04         78.0
 2017-06-04         79.0
 2017-06-04         77.0
 2017-06-05         78.0
 2017-06-05         76.0
 2017-06-05         74.0
 2017-06-05         75.0
 2017-06-05         78.0
 2017-06-05         81.0
 2017-06-05         80.0
 2017-06-06         79.0
 2017-06-06         75.0
 2017-06-06         78.0
 2017-06-06         80.0
 2017-06-06         74.0
 2017-06-06         80.0
 2017-06-06         75.0
 2017-06-07         79.0
 2017-06-07         78.0
 2017-06-07         75.0
 2017-06-07         80.0
 2017-06-07         75.0
 2017-06-07         81.0
 2017-06-07         79.0
 2017-06-08         77.0
 2017-06-08         80.0
 2017-06-08         75.0
 2017-06-08         78.0
 2017-06-08         79.0
 2017-06-08         76.0
 2017-06-08         75.0
 2017-06-09         80.0
 2017-06-09         72.0
 2017-06-09         81.0
 2017-06-09         80.0
 2017-06-09         78.0
 2017-06-09         78.0
 2017-06-10         77.0
 2017-06-10         72.0
 2017-06-10         74.0
 2017-06-10         78.0
 2017-06-10         75.0
 2017-06-10         75.0
 2017-06-11         79.0
 2017-06-11         73.0
 2017-06-11         74.0
 2017-06-11         76.0
 2017-06-11         79.0
 2017-06-11         81.0
 2017-06-12         83.0
 2017-06-12         76.0
 2017-06-12         74.0
 2017-06-12         79.0
 2017-06-12         74.0
 2017-06-12         80.0
 2017-06-13         75.0
 2017-06-13         81.0
 2017-06-13         73.0
 2017-06-13         76.0
 2017-06-13         76.0
 2017-06-13         77.0
 2017-06-13         80.0
 2017-06-14         79.0
 2017-06-14         80.0
 2017-06-14         80.0
 2017-06-14         76.0
 2017-06-14         74.0
 2017-06-14         78.0
 2017-06-14         74.0
 2017-06-15         78.0
 2017-06-15         78.0
 2017-06-15         77.0
 2017-06-15         75.0
 2017-06-15         77.0
 2017-06-15         77.0
 2017-06-15         78.0
 2017-06-16         73.0
 2017-06-16         80.0
 2017-06-16         78.0
 2017-06-16         79.0
 2017-06-16         80.0
 2017-06-16         76.0
 2017-06-16         74.0
 2017-06-17         77.0
 2017-06-17         79.0
 2017-06-17         72.0
 2017-06-17         77.0
 2017-06-17         80.0
 2017-06-17         78.0
 2017-06-18         77.0
 2017-06-18         72.0
 2017-06-18         78.0
 2017-06-18         77.0
 2017-06-18         77.0
 2017-06-18         75.0
 2017-06-19         78.0
 2017-06-19         78.0
 2017-06-19         76.0
 2017-06-19         78.0
 2017-06-19         80.0
 2017-06-19         72.0
 2017-06-19         77.0
 2017-06-20         72.0
 2017-06-20         74.0
 2017-06-20         77.0
 2017-06-20         79.0
 2017-06-20         75.0
 2017-06-20         78.0
 2017-06-21         74.0
 2017-06-21         76.0
 2017-06-21         82.0
 2017-06-21         79.0
 2017-06-21         80.0
 2017-06-21         75.0
 2017-06-22         80.0
 2017-06-22         81.0
 2017-06-22         77.0
 2017-06-22         76.0
 2017-06-22         72.0
 2017-06-22         80.0
 2017-06-23         78.0
 2017-06-23         76.0
 2017-06-23         71.0
 2017-06-23         72.0
 2017-06-23         76.0
 2017-06-23         76.0
 2017-06-23         79.0
 2017-06-24         74.0
 2017-06-24         77.0
 2017-06-24         82.0
 2017-06-24         80.0
 2017-06-24         73.0
 2017-06-25         80.0
 2017-06-25         73.0
 2017-06-25         79.0
 2017-06-25         71.0
 2017-06-25         80.0
 2017-06-26         79.0
 2017-06-26         81.0
 2017-06-26         77.0
 2017-06-26         73.0
 2017-06-26         80.0
 2017-06-26         81.0
 2017-06-26         82.0
 2017-06-27         76.0
 2017-06-27         77.0
 2017-06-27         81.0
 2017-06-27         74.0
 2017-06-27         80.0
 2017-06-27         80.0
 2017-06-28         79.0
 2017-06-28         77.0
 2017-06-28         77.0
 2017-06-28         74.0
 2017-06-28         79.0
 2017-06-28         80.0
 2017-06-29         79.0
 2017-06-29         76.0
 2017-06-29         76.0
 2017-06-29         79.0
 2017-06-29         76.0
 2017-06-29         76.0
 2017-06-29         78.0
 2017-06-30         76.0
 2017-06-30         74.0
 2017-06-30         81.0
 2017-06-30         75.0
 2017-06-30         74.0
 2017-06-30         75.0
 2017-06-30         75.0

In [14]:
# Use Pandas to calcualte the summary statistics for the precipitation data
df.describe()

       temperature
count   191.000000
mean     77.219895
std       2.622538
min      71.000000
25%      75.000000
50%      77.000000
75%      79.000000
max      83.000000

# Challenge